---
# Ignore misconfigurations
misconfigurations:
  # Offending values are hardcoded within core module variable `connectivty`. Until networking is removed, these must be ignored.
  - id: AVD-AZU-0050 # Security group rule allows unrestricted ingress to SSH port from any IP address.
  - id: AVD-AZU-0047 # Security group rule allows unrestricted ingress from any IP address.
