# yaml-language-server: $schema=https://json.schemastore.org/github-issue-forms.json
# https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-githubs-form-schema
---
name: ✔️ Task
description: Task to be done
title: "[TASK] "
labels: [type/task]
type: Task
projects: ["microsoft/1366"]
body:
  - type: textarea
    id: description
    attributes:
      label: 📝 Description
      description: A clear and concise description of the task.
      placeholder: A clear and concise description of the task.
    validations:
      required: true

  - type: checkboxes
    id: terms
    attributes:
      label: 🔰 Code of Conduct
      description: By submitting this issue, you agree to follow [`Code of Conduct`](../blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct.
          required: true
