# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
---
name: Labeler
on:
  pull_request:

permissions:
  contents: read
  pull-requests: write

jobs:
  main:
    runs-on: ubuntu-24.04
    steps:
      - name: Run Labeler
        if: github.event.pull_request.head.repo.full_name == github.event.pull_request.base.repo.full_name
        uses: actions/labeler@634933edcd8ababfe52f92936142cc22ac488b1b # v6.0.1
        with:
          sync-labels: true
