# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
---
name: Labels

on:
  push:
    branches:
      - main
    paths:
      - .github/labels.yml
      - .github/workflows/labels.yml
  pull_request:
    paths:
      - .github/labels.yml
      - .github/workflows/labels.yml
  label:

permissions:
  contents: read
  issues: write

jobs:
  labels:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Create issue on manual change
        if: ${{ github.event_name == 'label' && !contains(github.actor, '[bot]') }}
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        with:
          github-token: ${{ github.token }}
          script: |
            const { default: script } = await import(`${process.env.GITHUB_WORKSPACE}/.github/scripts/label_issue.mjs`)
            await script({context, github, core})

      - name: Run Labeler
        if: ${{ !contains(github.actor, '[bot]') }}
        uses: crazy-max/ghaction-github-labeler@24d110aa46a59976b8a7f35518cb7f14f434c916 # v5.3.0
        with:
          github-token: ${{ github.token }}
          dry-run: ${{ github.event_name == 'pull_request' }}
